on:
  push:
    branches:
      - master
name: build gatsby
jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          name: "daniyalnagori" # Not required, default to action's maintainer
          email: "daniyalnagori@yahoo.com" # Not required, default to action's maintainer
          contentfulSpace: ${{ secrets.CONTENTFUL_SPACEID }} # Your Space ID in Contentful
          contentfulToken: ${{ secrets.CONTENTFUL_ACCESSTOKEN }} # Your access token of Contentful

      - name: yarn install
        run: yarn install

      - name: gatsby build
        env:
          GH_API_KEY: ${{ secrets.PA_TOKEN }}

        run: yarn build

      - name: deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.PA_TOKEN }}
          BUILD_DIR: "public/"
